name: Build and Push Langfuse

on:
  push:
    branches: [ "v2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker version

      - run: |
          docker build \
            --build-arg NEXT_PUBLIC_BASE_PATH=/langfuse \
            -t langfuse-test \
            -f web/Dockerfile .
