name: Build and Push Langfuse

on:
  push:
    branches: [ "v2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::162343471462:role/GitHubActionsECRPushRole
          aws-region: ap-northeast-1

      - run: |
          aws ecr get-login-password \
            | docker login \
              --username AWS \
              --password-stdin 123456789012.dkr.ecr.ap-northeast-1.amazonaws.com

      - run: |
          docker build -t langfuse .
          docker tag langfuse:latest 123456789012.dkr.ecr.ap-northeast-1.amazonaws.com/langfuse:latest
          docker push 123456789012.dkr.ecr.ap-northeast-1.amazonaws.com/langfuse:latest
